<!DOCTYPE html>
<html>
<head>
	<title>My Website</title>
	<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
	<header>
		<h1>My Website</h1>
		<nav>
			<ul>
				<li><a href="#">Home</a></li>
				<li><a href="#">About</a></li>
				<li><a href="#">Contact</a></li>
			</ul>
		</nav>
	</header>
	<main>
		<h2>Welcome to my website</h2>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eget eros non enim bibendum fringilla. Nam feugiat urna id nulla faucibus malesuada.</p>
		<img src="media/image.jpg">
	</main>
</body>
</html>
body {
	font-family: Arial, sans-serif;
}

header {
	background-color: #333;
	color: #fff;
	padding: 20px;
}

nav {
	float: right;
}

nav ul {
	margin: 0;
	padding: 0;
	list-style: none;
}

nav li {
	display: inline-block;
	margin-left: 20px;
}

nav a {
	color: #fff;
	text-decoration: none;
}

main {
	padding: 20px;
}

img {
	max-width: 100%;
	height: auto;
}
